### ISSUE TITLE
What is the motivation for omitting array serialization?

### ISSUE THREAD

**Issue by timothy-shields** [Code-Sharp/Newtonsoft.Msgpack#1]
What is the motivation for this statement?

> This supports only Msgpack Map serialization, I think that array serialization doesn't really fit here.

**Comment by darkl** [comment]
[msgpack-cli](http://cli.msgpack.org/) supports two serialization methods: map and array serialization. The difference is that in map serialization, every field name is written before its field value (When serializing composite classes), and in array serialization, the field names array omitted - instead, the fields are stored in an array.

The problem with the array method is that you need to know the exact order of the fields and that doesn't really fit for this kind of "JSON" dynamic serialization, where field order tend to change between different versions of the application or different platforms. 

msgpack-cli solves this problem using a custom attribute (or DataMemberAttribute's Position property), but that makes things more complicated.

**Comment by timothy-shields** [comment]
I will rephrase. Does your library support serializing something like the following?

    class Matrix
    {
         public int[] Shape { get; set; }
         public double[] Data { get; set; }
    }

**Comment by darkl** [comment]
Yeah, should work fine.
