### ISSUE TITLE
Newest version of Newtosoft.Json support

### ISSUE THREAD

**Issue by brunoblank** [Code-Sharp/Newtonsoft.Msgpack#3]
Hi,

Really nice package! Just what I was looking for.

However, we could not integrate the package since we are using Newtonsoft.Json 7.0.1 and the package has a dependency for Newtosoft.Json < 7.0.

Will there be an update soon?

Thanks
/Bruno

**Comment by darkl** [comment]
Hi, here's the deal: I can update the library to use Newtonsoft.Json 7.0.1,
but then users won't be able to use libraries that depend on a lower
version (I think a lot of libraries depend on 6.0.5 and etc).

I can also remove the dependency's upper bound, but then it will result
with adding an assembly binding which I'm not sure is desired.

Do you have any other ideas?

Elad

**Comment by prestoja** [comment]
We're running into the same problem.

As long as you don't know of any incompatibilities with 7.0+ I would suggest removing the upper limit.

I agree that it is better to avoid binding redirects when possible, but not at the expense of restricting user's ability to use the latest stable versions of other (very popular) packages.

**Comment by brunoblank** [comment]
I agree with @prestoja

**Comment by darkl** [comment]
Ok, I'll probably work on this on the weekend.

**Comment by darkl** [comment]
Hi, I removed the upper bounds for both Newtonsoft.Json and msgpack-cli.
Hope it works fine for you.

Elad

**Comment by brunoblank** [comment]
Awesome, I will check it out.

Thanks for the quick help!
/Bruno

**Comment by prestoja** [comment]
Thanks!



On Sat, Nov 14, 2015 at 9:16 AM -0800, "Bruno Blank" <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome, I will check it out.

Thanks for the quick help!
/Bruno

-
